site_name: FlowerPower-MQTT Documentation
site_url: https://your-docs-url.com # Replace with actual URL
repo_url: https://github.com/legout/flowerpower-mqtt
repo_name: legout/flowerpower-mqtt
edit_uri: edit/main/docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/legout
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/legout

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            paths: [src]
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            line_length: 80
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            members_order: source
            show_bases: true
            show_submodules: true
            group_by_category: true
            show_labels: true

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Core Concepts: core-concepts.md
    - Programmatic Usage:
      - Overview: programmatic-usage/index.md
      - Configuration: programmatic-usage/configuration.md
      - MQTT Plugin: programmatic-usage/mqtt-plugin.md
      - Subscriptions: programmatic-usage/subscriptions.md
    - CLI Reference: cli-reference.md
    - Examples: examples.md
  - Advanced Guides:
    - FlowerPower Integration: flowerpower-integration.md
    - Asynchronous Processing: async-processing.md
    - Monitoring: monitoring.md
    - Other Advanced Topics: advanced-topics.md
  - API Reference: api/index.md
  - Project:
    - Contributing: contributing.md
    - Changelog: changelog.md